[[redirects]]
from = "/<path-to-access-cors-url>"
to = "https://wifm.site/"
status = 200
force = true
headers = {X-From = "Netlify"}
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[build]
command = "npm run build"  # 프로젝트 빌드 명령어를 설정합니다.

